### ISSUE TITLE
Unable to authenticate at present (set_id=username): missing or misplaced { or }

### ISSUE THREAD

**Issue by himbeere** [Exim/exim#38] opened 2015-11-27 10:11 UTC
Hello.

First of all. Thanks for your work.

I spotted a bug when using the following authenticator:

```
  driver                     = plaintext
  public_name                = PLAIN
  server_advertise_condition = ${if eq{$tls_cipher}{}{false}{true}}
  server_prompts             = :
  server_set_id              = $auth2

  server_condition           = "\
        ${if exists{/etc/exim/passwd}\
          {${lookup{$auth2}lsearch{/etc/exim/passwd}\
            {${if crypteq{$auth3}{\\\{md5\\\}${extract{1}{:}{$value}{$value}fail}}\
              {true}{false} }}\
            {${if pam{$auth2:${sg{$auth3}{:}{::}} }\
              {true}{false}} } }}\
          {${if pam{$auth2:${sg{$auth3}{:}{::}} }\
            {true}{false}} }}"
```

When i try to authenticate and use a wrong user i get: Unable to authenticate at present (set_id=username): missing or misplaced { or } instead of wrong username or password. Any hints how to solve this?

thanks and cheers

**Comment by george-vieira** [comment] 2016-01-01 12:38
this is not a bug and should be placed in more appropriate places like the mailling list.
basic answer is you missed the { in the crypteq line just after the md5 closing bracket where the ${extract begins.

server_condition           = "\
        ${if exists{/etc/exim/passwd}\
          {${lookup{$auth2}lsearch{/etc/exim/passwd}\
            {${if crypteq{$auth3}{\\\{md5\\\}{${extract{1}{:}{$value}{$value}fail}}\
              {true}{false} }}\
            {${if pam{$auth2:${sg{$auth3}{:}{::}} }\
              {true}{false}} } }}\
          {${if pam{$auth2:${sg{$auth3}{:}{::}} }\
            {true}{false}} }}"

Not sure why you have all the backslashes and the double quotes around your whole condition and I'm only going off the brackets alone.

**Comment by himbeere** [comment] 2016-01-01 18:21
Hello.

Thanks for your answer. But adding the { does not fix my issue. The authenticator then does not work at all after that anymore. Just to mention it. I took the authenticator from https://github.com/Exim/exim/wiki/AuthenticatedSmtpUsingPamAndPasswords. Any other suggestions? Should i switch to the exim mailing list?

thanks and cheers
t.

**Comment by george-vieira** [comment] 2016-01-01 21:54
Sorry, I really shouldn't look at acl rules with 3764287 brackets at midnight hehe. Also noticed my \\\ for some reason was removed to just 1 \ which isn't right and should've been \\\, not sure what removed it.

you didn't mention what version of exim/distro, etc as it may help too.

I actually tested your original code on the only server I had a passwd account on it with exim command line and seems to work fine for me on debian/wheezy 4.80
Removed the "" around the condition and removed the end \ and made it all 1 line. Then replaced my $auth2 and $auth3 with my test username and password, seemed to return true and false. Looks like for my system the very last check validated the password by fudging the password itself to an incorrect value changed the result. So I guess it used PAM in my system.

```
root@tefnut:~ $ exim -be '${if exists{/etc/exim/passwd}          {${lookup{eitadmin}lsearch{/etc/exim/passwd}            {${if crypteq{MyPassw0rd}{\\\{md5\\\}${extract{1}{:}{$value}{$value}fail}}              {true}{false} }}            {${if pam{eitadmin:${sg{MyPassw0rd}{:}{::}} }              {true}{false}} } }}          {${if pam{eitadmin:${sg{MyPassw0rdaaa}{:}{::}} }            {true}{false}} }}'
false

root@tefnut:~ $ exim -be '${if exists{/etc/exim/passwd}          {${lookup{eitadmin}lsearch{/etc/exim/passwd}            {${if crypteq{MyPassw0rd}{\\\{md5\\\}${extract{1}{:}{$value}{$value}fail}}              {true}{false} }}            {${if pam{eitadmin:${sg{MyPassw0rd}{:}{::}} }              {true}{false}} } }}          {${if pam{eitadmin:${sg{MyPassw0rd}{:}{::}} }            {true}{false}} }}'
true
```

You could do a fake smtp connection in debug mode and see the output. Because it's auth you'll have to encode your user/pass and sent it to the server.
Use the example below and treat it like a telnet localhost 25 on your server and perform the authentication, watch the debug output.
Otherwise try the mailling list, you'll get a quicker response.

$ exim -d -bh 1.2.3.4

**Comment by himbeere** [comment] 2016-01-02 11:58
Thanks so far. Will switch to the mailing list.

cheers
t.

**Comment by nigelm** [comment] 2016-02-24 16:38
Dormant issue - closing

**Closed by nigelm** 2016-02-24 16:38 UTC
Labels: Support Help
